name: xx230v build
on:
  push:
  workflow_dispatch:
    inputs:
      verbose:
        type: choice
        required: false
        default: "sc"
        options:
          - "sc"
          - "s"
          - ""
  schedule:
    - cron: 0 12 */2 * *

jobs:
  openwrt_build:
    secrets: inherit
    uses: ./.github/workflows/openwrt-build.yaml
    name: Build to en7523
    with:
       openwrt_repository: airoha_en7523/openwrt
       verbose: ${{ github.event_name == 'workflow_dispatch' && inputs.verbose || 'sc' }}
       config_file: en7523.config

  release:
    runs-on: ubuntu-latest
    needs: openwrt_build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
          # merge-multiple: true
          # pattern: target_*

      - name: Create release
        uses: akkuman/gitea-release-action@main
        with:
          name: v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body: |
              # EN7523 [Build](/actions/runs/${{ github.run_number }})

              build targets

              - tplink xx230v v1
              - tplink xx530v v1
              - tplink ex530v v1
          files: |
            **/*/targets.tar
            **/*/targets/**/*
            !**/*/targets/**/*.apk
            !**/*/targets/**/*.ipkg
