name: Airoha EN7523 build
run-name: Airoha EN7523 build - ${{ github.run_number }} (${{ github.run_id }}) - Actor ${{ github.actor || 'Unknown' }}

on:
  push:
  schedule:
    - cron: 0 15 */3 * *
  workflow_dispatch:
    inputs:
      run-tmate:
        type: boolean
        required: false
        default: false
        description: Run tmate session for debug
      verbose:
        type: choice
        required: false
        default: "s"
        description: Openwrt build verbose level
        options:
          - "none"
          - "sc"
          - "s"

concurrency:
  cancel-in-progress: true
  group: airoha_en7523_build-${{ github.ref }}

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_openwrt:
    name: Build Openwrt
    uses: ./.github/workflows/generic.yaml
    with:
      openwrt_repository: airoha_en7523/openwrt
      verbose: ${{ github.event_name == 'workflow_dispatch' && inputs.verbose || 's' }}
      config_file: en7523
      files_folder: en7523_files
      run-tmate: ${{ github.event_name == 'workflow_dispatch' && inputs.run-tmate || false }}

  release:
    name: Create Release
    needs: build_openwrt
    runs-on: ubuntu-latest
    steps:
      - name: Download actifacts
        uses: actions/download-artifact@v3

      - name: Uncompress build artifacts
        run: |
          find . -type f -name "artifacts_en7523.tar.xz" -exec mv -fv {} artifacts_en7523.tar.xz \;
          xz -d artifacts_en7523.tar.xz
          tar -xvf artifacts_en7523.tar

      - name: Sirherobrine23 Create release
        uses: akkuman/gitea-release-action@main
        with:
          name: Build Action ${{ github.run_id }}
          tag_name: v${{ github.run_id }}
          body_path: release_body.md
          server_url: https://sirherobrine23.com.br
          repository: airoha_en7523/builds
          token: ${{ secrets.GITEA_TOKEN }}
          files: |
            build.tar.*
            bin/targets/**/*